[ClassVersion("1.0.0.0"), FriendlyName("xWebAuthorization")]
class MSFT_xWebAuthorization : OMI_BaseResource
{
	[Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
	[Write,ValueMap{"Allow","Deny"},Values{"Allow", "Deny"}] String Action;
	[Write,ValueMap{"Users","Roles"},Values{"Users","Roles"},Required] String ResourceType;
	[Key] String Value;
	[Key] String PSPath;
	[Key] String Location;
	[Write] String Verbs;
};